title: HongguLiu
author: Honggu Liu
theme: jekyll-theme-architect
description: This is a homepage of Honggu Liu
timezone: Asia/Shanghai #网站时区
root: /
source_dir: source #资源文件夹，这个文件夹用来存放内容
public_dir: public #公共文件夹，这个文件夹用于存放生成的站点文件
tag_dir: tags #标签文件夹
archive_dir: archives #归档文件夹
category_dir: categories #分类文件夹
code_dir: downloads/code #Include code 文件夹
